### ISSUE TITLE
Can't run tigase server

### ISSUE THREAD

**Issue by mgben16** [tigase/tigase-server#126]
**Describe the bug**
Hello, I'm trying to setup tigase server for a school project. I'm using Ubuntu 20.04.3 LTS. After cloning the repository (git clone https://github.com/tigase/tigase-server.git), compiling using maven (mvn package test) and setting JAVA_HOME in etc/tigase.conf file, I get the following error when trying to run the server (in tigase-console.log file):

==========
STARTED Tigase mié 05 ene 2022 16:26:49 CET using:
    ./scripts/tigase.sh start etc/tigase.conf 
==========
Exception in thread "main" java.lang.NoClassDefFoundError: tigase.xml.XMLNodeIfc
	at tigase.server.XMPPServer.main(XMPPServer.java:137)
Caused by: java.lang.ClassNotFoundException: tigase.xml.XMLNodeIfc
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:766)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1081)
	... 1 more

How could I solve this problem?

(This is my very first service administration project, so I apologize for any errors or missing information)

**Comment by woj-tek** [comment]
I would suggest taking a look at [Quick Start guide](https://docs.tigase.net/tigase-server/master-snapshot/Administration_Guide/html/#QuickStart) and using pre-build packages available in release section (especially if this is "administration project").

Otherwise, you would have to include all require dependencies (xmltools, utils and jdbc drivers for the selected database at the very least).
