### ISSUE TITLE
Error trying to install Tigase server on GCP machine

### ISSUE THREAD

**Issue by blacar** [tigase/tigase-server#200]
**I have a problem with…**
Installing Tigase 8.1.0 on GCP machine

**Details (please complete the following information):**
 - Tigase version 8.1.0

root@tigase-test:/opt/tigase-server-8.1.0-b10857# java -version
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu120.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)

- Ubuntu 20.04

- Mysql 5.7 at GCP Cloud SQL
(NOTE log_bin_trust_function_creations is set True)

- This is the generated jdbc `jdbc:mysql://localhost/tigasedb?user=tigase&password=[password]&useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true`

**Description**

1º We download `https://github.com/tigase/tigase-server/releases/download/tigase-server-8.1.0/tigase-server-8.1.0-b10857-dist-max.tar.gz`
2º We untar/unzip and execute `./scripts/tigase.sh start etc/tigase.conf`
3º We navigate through the wizard and eventually see this:

```
- Checking connection to DB --> OK
- Checking if DB exists --> OK
- Loading Common Schema Files --> OK
- Loading schema: Tigase Message Archiving Component, version 2.1.9-b269/1a9d06e9 (database version: none) --> OK
- Loading schema: Tigase XMPP Server (Core), version 0.0.0 (database version: none) --> *SKIPPED*

Here I have an additional info box:

- Required Schema is already loaded in the correct version
- Failure: FUNCTION tigasedb. TigGetDBProperty does not exist
- Failure: FUNCTION tigasedb. TigGetDBProperty does not exist

Then the installation continues

- Loading Schema: Tigase MUC Component, version: 3.1.0-b639/fd3d211f (database vesion: none) --> OK
- Loading Schema: Tigase PubSub Component, version 4.1.0-b715/821100b (database version: none) --> OK

- Adding XMPP Admin accounts --> WARNING

-- Problem accessing repository for user: admin@tigase-test.my.database

- Post installation action --> OK
```

After this trying to start the server we get this:

```
[2023-05-16 19:51:51:021] [SEVERE  ] [                  main ] UserRepoRepository.setRepo()     : Problem with adding 'vhost-manager' user to the database
tigase.db.TigaseDBException: Error adding user to repository: 
	at tigase.db.jdbc.JDBCRepository.addUser(JDBCRepository.java:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at tigase.stats.StatisticsInvocationHandler.invoke(StatisticsInvocationHandler.java:75)
	at com.sun.proxy.$Proxy110.addUser(Unknown Source)
	at tigase.db.UserRepositoryMDImpl.addUser(UserRepositoryMDImpl.java:69)
	at tigase.db.comp.UserRepoRepository.setRepo(UserRepoRepository.java:115)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at tigase.kernel.BeanUtils.setValue(BeanUtils.java:172)
	at tigase.kernel.core.Kernel.inject(Kernel.java:1229)
	at tigase.kernel.core.Kernel.injectDependencies(Kernel.java:1315)
	at tigase.kernel.core.Kernel.initBean(Kernel.java:131)
	at tigase.kernel.core.Kernel.injectDependencies(Kernel.java:1254)
	at tigase.kernel.core.Kernel.injectDependency(Kernel.java:866)
	at tigase.kernel.core.Kernel.injectDependencies(Kernel.java:880)
	at tigase.kernel.core.Kernel.registerBean(Kernel.java:1101)
	at tigase.kernel.core.BeanConfigBuilder.execWithoutInject(BeanConfigBuilder.java:112)
	at tigase.kernel.core.BeanConfigBuilder.exec(BeanConfigBuilder.java:99)
	at tigase.db.beans.SDRepositoryBean.beanConfigurationChanged(SDRepositoryBean.java:97)
	at tigase.db.beans.SDRepositoryBean.initialize(SDRepositoryBean.java:125)
	at tigase.kernel.core.Kernel.initBean(Kernel.java:136)
	at tigase.kernel.core.Kernel.injectDependencies(Kernel.java:1254)
	at tigase.kernel.core.Kernel.injectDependency(Kernel.java:866)
	at tigase.kernel.core.Kernel$DelayedDependenciesInjection.inject(Kernel.java:1533)
	at tigase.kernel.core.Kernel.finishDependecyDelayedInjection(Kernel.java:565)
	at tigase.kernel.core.Kernel.initBean(Kernel.java:128)
	at tigase.kernel.core.Kernel.injectDependencies(Kernel.java:1254)
	at tigase.kernel.core.Kernel.initBean(Kernel.java:131)
	at tigase.kernel.core.Kernel.injectDependencies(Kernel.java:1254)
	at tigase.kernel.core.Kernel.injectDependency(Kernel.java:866)
	at tigase.kernel.core.Kernel$DelayedDependenciesInjection.inject(Kernel.java:1533)
	at tigase.kernel.core.Kernel.finishDependecyDelayedInjection(Kernel.java:565)
	at tigase.kernel.core.Kernel.initBean(Kernel.java:128)
	at tigase.kernel.core.Kernel.injectDependencies(Kernel.java:1254)
	at tigase.kernel.core.Kernel.initBean(Kernel.java:131)
	at tigase.kernel.core.Kernel.getInstance(Kernel.java:303)
	at tigase.server.Bootstrap.start(Bootstrap.java:327)
	at tigase.server.XMPPServer.start(XMPPServer.java:188)
	at tigase.server.XMPPServer.main(XMPPServer.java:141)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: PROCEDURE tigasedb.TigAddUserPlainPw does not exist
```

Any known problem running tigase on GCP machines?

**Comment by blacar** [comment]
This was a mistake and a miscommunication on our side

**Comment by woj-tek** [comment]
To shed more light - correct configuration option is: `log_bin_trust_function_creators`.
