### ISSUE TITLE
issue while running tigase

### ISSUE THREAD

**Issue by Ucheha** [tigase/tigase-server#22]
am getting below exception while running tigase, 
am using java 8

java.lang.UnsupportedClassVersionError: module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at tigase.util.ClassUtil.getClassesFromNames(ClassUtil.java:176)
        at tigase.util.ClassUtil.getClassesFromClassPath(ClassUtil.java:133)
        at tigase.util.reflection.ClassUtilBean.initialize(ClassUtilBean.java:90)
        at tigase.server.Bootstrap.start(Bootstrap.java:288)
        at tigase.server.XMPPServer.start(XMPPServer.java:188)
        at tigase.server.XMPPServer.main(XMPPServer.java:142)

**Comment by woj-tek** [comment]
Which Tigase version do you use? Which components (can you share your configuration file)?

As stated in [Minimum Requirements](https://docs.tigase.net/tigase-server/master-snapshot/Administration_Guide/html/#_minimum_requirements):
> Java Development Kit (JDK) 11 (LTS) - We recommend OpenJDK
> It may be possible to run Tigase XMPP Server with JDK v8 but it is not  recommended as not all features will be available and you may encounter  startup issues.

**Comment by Ucheha** [comment]
tigase version 8.0.0

components:
Loading component: vhost-man :: componentInfo{Title=Tigase XMPP Server, Version=8.0.0-b5343/a5de0ed9, Class=tigase.vhosts.**VHostManager**}
Loading component: cluster-contr :: componentInfo{Title=Tigase XMPP Server, Version=8.0.0-b5343/a5de0ed9, Class=tigase.cluster.**ClusterController**}
Loading component: message-router :: componentInfo{Title=Tigase XMPP Server, Version=8.0.0-b5343/a5de0ed9, Class=tigase.server.**MessageRouter**}
Loading component: bosh :: componentInfo{Title=Tigase XMPP Server, Version=8.0.0-b5343/a5de0ed9, Class=tigase.cluster.**BoshConnectionClustered**}
Loading component: cl-comp :: componentInfo{Title=Tigase XMPP Server, Version=8.0.0-b5343/a5de0ed9, Class=tigase.cluster.**ClusterConnectionManager**}
Loading component: stats :: componentInfo{Title=Tigase XMPP Server, Version=8.0.0-b5343/a5de0ed9, Class=tigase.stats.**StatisticsCollector**}
Loading component: sess-man :: componentInfo{Title=Tigase XMPP Server, Version=8.0.0-b5343/a5de0ed9, Class=tigase.cluster.**SessionManagerClustered**}
Loading component: c2s :: componentInfo{Title=Tigase XMPP Server, Version=8.0.0-b5343/a5de0ed9, Class=tigase.cluster.**ClientConnectionClustered**}
Loading component: ws2s :: componentInfo{Title=Tigase XMPP Server, Version=8.0.0-b5343/a5de0ed9, Class=tigase.cluster.**WebSocketClientConnectionClustered**}
Loading component: monitor :: componentInfo{Title=Tigase XMPP Server, Version=8.0.0-b5343/a5de0ed9, Class=tigase.monitor.**MonitorComponent**}
Loading component: eventbus :: componentInfo{Title=Tigase XMPP Server, Version=8.0.0-b5343/a5de0ed9, Class=tigase.eventbus.component.**EventBusComponent**}
Loading component: s2s :: componentInfo{Title=Tigase XMPP Server, Version=8.0.0-b5343/a5de0ed9, Class=tigase.server.xmppserver.**S2SConnectionManager**}


plugins:

Loading plugin: ac-roster-presence=10:2063 ...  , version: 1
Loading plugin: urn:ietf:params:xml:ns:xmpp-session=2:10319 ...         , version: 1
Loading plugin: default-handler=32:644 ...      , version: 1
Loading plugin: presence-state=32:644 ...       , version: 1
Loading plugin: vcard-xep-0292=8:2579 ...       , version: 1
Loading plugin: session-open=16:1289 ...        , version: 1
Loading plugin: urn:xmpp:csi:0=8:2579 ...       , version: 1
Loading plugin: http://jabber.org/protocol/stats=8:2579 ...     , version: 1
Loading plugin: urn:xmpp:blocking=8:2579 ...    , version: 1
Loading plugin: http://jabber.org/protocol/commands=8:2579 ...  , version: 1
Loading plugin: starttls=2:10319 ...    , version: 1
Loading plugin: urn:xmpp:ping=2:10319 ...       , version: 1
Loading plugin: m800msgoffline=10:2063 ...      , version: 1
Loading plugin: vcard-temp=2:10319 ...  , version: 1
Loading plugin: jabber:iq:mcast:rooms=2:10319 ...       , version: 1
Loading plugin: urn:ietf:params:xml:ns:xmpp-bind=2:10319 ...    , version: 1
Loading plugin: presence-subscription=32:644 ...        , version: 1
Loading plugin: jabber:iq:auth=1:20639 ...      , version: 1
Loading plugin: urn:ietf:params:xml:ns:xmpp-sasl=1:20639 ...    , version: 1
Loading plugin: urn:xmpp:time=8:2579 ...        , version: 1
Loading plugin: message-carbons=8:2579 ...      , version: 1
Loading plugin: xep0012=12:1719 ...     , version: 1
Loading plugin: acker2=10:2063 ...      , version: 1
Loading plugin: disco=2:10319 ...       , version: 1
Loading plugin: zlib=8:2579 ...         , version: 1
Loading plugin: jabber:iq:register=2:10319 ...  , version: 1
Loading plugin: session-close=32:644 ...        , version: 1
Loading plugin: message=8:2579 ...      , version: 1

**Comment by woj-tek** [comment]
I assume that you've build your components with JDK8?

Version 8.0.0 (stable) should run with JVM8 without issue.

Please run this command, and share it's output, in your tigase-server installation directory:
```
for f in `ls jars/*.jar` ; do echo ${f}: `unzip -qc ${f} META-INF/MANIFEST.MF | grep "Build-Jdk"` ;  done
```
