### ISSUE TITLE
NoSuchElementException on startup

### ISSUE THREAD

**Issue by davidemarrone** [tigase/tigase-server#49]
During the startup of an instance of the cluster I have logged this exception with the version 8.1.0-b10857

```
[2020-08-05 19:54:23:960] [WARNING ] [ResultsListener-socketReadThread-11 ] SocketThread$ResultsListener.run(): Protocol execution exception.
java.util.NoSuchElementException
	at java.base/java.util.concurrent.ConcurrentLinkedDeque.screenNullResult(ConcurrentLinkedDeque.java:764)
	at java.base/java.util.concurrent.ConcurrentLinkedDeque.removeLast(ConcurrentLinkedDeque.java:966)
	at tigase.stats.MaxDailyCounterQueue.add(MaxDailyCounterQueue.java:48)
	at tigase.cluster.ClusterConnectionManager.nodeConnected(ClusterConnectionManager.java:328)
	at tigase.cluster.ClusterController.nodeConnected(ClusterController.java:126)
	at tigase.cluster.ClusterConnectionManager.serviceConnected(ClusterConnectionManager.java:777)
	at tigase.cluster.ClusterConnectionManager.processHandshake(ClusterConnectionManager.java:908)
	at tigase.cluster.ClusterConnectionManager.processSocketData(ClusterConnectionManager.java:424)
	at tigase.server.ConnectionManager.packetsReady(ConnectionManager.java:347)
	at tigase.server.ConnectionManager.packetsReady(ConnectionManager.java:61)
	at tigase.net.IOService.call(IOService.java:202)
	at tigase.xmpp.XMPPIOService.call(XMPPIOService.java:146)
	at tigase.xmpp.XMPPIOService.call(XMPPIOService.java:51)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by woj-tek** [comment]
Thank you for the report. Could you share more details? Are there any other entries in the logs? Do you run Tigase in cluster mode (if yes - how many nodes)?

**Comment by davidemarrone** [comment]
yes, we are running tigase in cluster mode, is same new cluster with all the logs from previous tickets, there isn't any other particular error. The cluster was running with 2 nodes and I have turned on other 2 nodes, on the node 3 I have seen this exception when it has started

**Comment by woj-tek** [comment]
Does it impact in any way operation of the cluster? (unlikely)

**Comment by davidemarrone** [comment]
no, it works correctly without problems
