### ISSUE TITLE
Can't Create MUC room

### ISSUE THREAD

**Issue by gandhi-wibowo** [tigase/tigase-server#93]
**I have a problem with creating muc room**
I try open tigase web admin, and go to menu -> Other -> Create Room.
And what i have is error display

```
javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: mucRepository for class: tigase.admin.Script151
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:320)
	at org.codehaus.groovy.jsr223.GroovyCompiledScript.eval(GroovyCompiledScript.java:71)
	at tigase.server.script.Script.runCommand(Script.java:122)
	at tigase.server.BasicComponent.processScriptCommand(BasicComponent.java:903)
	at tigase.component.ComponenScriptCommandProcessor.processScriptCommand(ComponenScriptCommandProcessor.java:45)
	at tigase.component.modules.impl.AdHocCommandModule.processScriptAdHoc(AdHocCommandModule.java:143)
	at tigase.component.modules.impl.AdHocCommandModule.process(AdHocCommandModule.java:132)
	at tigase.component.modules.StanzaProcessor.process(StanzaProcessor.java:164)
	at tigase.component.modules.StanzaProcessor.processPacket(StanzaProcessor.java:85)
	at tigase.component.AbstractKernelBasedComponent.processPacket(AbstractKernelBasedComponent.java:81)
	at tigase.muc.MUCComponent.processPacket(MUCComponent.java:122)
	at tigase.server.AbstractMessageReceiver$QueueListener.run(AbstractMessageReceiver.java:1405)
Caused by: groovy.lang.MissingPropertyException: No such property: mucRepository for class: tigase.admin.Script151
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:309)
	at tigase.admin.Script151.run(Script151.groovy:42)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:317)
	... 11 more
```

**Details (please complete the following information):**
 - Tigase version: [e.g. 8.1.2]
 - Docker [version 3.3.3]
 - OS i running Docker [MacOs BigSur 20D91]
 
How i install

```
docker network create -d bridge tigase_cluster
```
```
docker run -d \
--name tigase_postgre \
--hostname tigase_postgre \
--network tigase_cluster \
-e POSTGRES_PASSWORD=root-password \
postgres
```

```
docker run -d \
--name tigase_cl1 \
--hostname tigase_cl1 \
--network tigase_cluster \
-v /Users/dizcoding/Docker/docker-tigase/tigase/etc/:/home/tigase/tigase-server/etc/ \
-v /Users/dizcoding/Docker/docker-tigase/tigase/certs/:/home/tigase/tigase-server/certs/ \
-v /Users/dizcoding/Docker/docker-tigase/tigase/data/:/home/tigase/tigase-server/data/ \
-e 'DB_ROOT_USER=postgres' \
-e 'DB_ROOT_PASS=root-password' \
-p 5222:5222 \
-p 5280:5280 \
-p 5290:5290 \
-p 8080:8080 \
tigase/tigase-xmpp-server:8.1.2
```

Ok, then i just finishing install from web http://localhost/8080
After all, there is no error showing when web setup progress. 

I dont know this is relate or not.

But, after finishing web setup. I do restart tigase server container
And this is showing on docker log window

```
Upgrading database schema...
=============================================================================
Schema upgrade finished
Data source: default with uri jdbc:postgresql://tigase_postgre/tigasedb?user=tigase_user&password=root-password&useSSL=false
Checking connection to database ok
Checking if database exists ok
Loading Common Schema Files skipped
Message: Required schema is already loaded in correct version
Skipping schema: Tigase Message Archiving Component, version: 2.1.0-b270/b48b562a (database version: 2.1.0-b270) skipped
Skipping schema: Tigase XMPP Server (Core), version: 8.1.1-b5650/86bb4486 (database version: 8.1.1-b5650) skipped
Skipping schema: Tigase MUC Component, version: 3.1.2-b649/5e056afa (database version: 3.1.2-b649) skipped
Skipping schema: Tigase PubSub Component, version: 4.1.0-b716/dded4fd1 (database version: 4.1.0-b716) skipped
Adding XMPP admin accounts error
Message: Database schema is invalid
Post installation action error
Message: Database schema is invalid

```

But when i see the tig_user table, my user account is stored on there.
I Dont know what is that mean of "Message: Database schema is invalid"

**Comment by woj-tek** [comment]
Thank you for reporting this. It's a know issue and will be fixed in upcoming 8.2.0.

For now you should use XMPP _way_ defined in the specification, see: [XEP-0045: Multi-User Chat: Creating a Room](https://xmpp.org/extensions/xep-0045.html#createroom)


Ref: https://projects.tigase.net/issue/muc-143
